### ISSUE TITLE
Figma Completo

### ISSUE THREAD

**Issue by CrimvaelVR** [JMCA2805/Proyecto_FrontEnd_II#22]
Debemos tener el Figma con una gran mayoria de lo que planteamos para nuestra pagina

Wireframes
Paleta
Fuente de Letra
Mockups
Diseño de la Base de Datos

**Comment by JMCA2805** [comment]
Primera parte del Figma

https://www.figma.com/file/YMWbQcDfx51qsN8FE08QiS/Proyecto-Front-II?type=design&node-id=0%3A1&mode=design&t=KGyAq1kzfZE9s8ih-1

**Comment by CrimvaelVR** [comment]
Hecho
